Added option for users to enable Finnish bank reference number
paytrail/paytrail-for-woocommerce pull request #141
Opened 2024-04-17 11:03 UTC by Taiteilija

This can be toggled from the plugin settings page and is required when using transaction-by-transaction settlements in paytrail

2024-04-17 12:53 UTC, loueranta-paytrail commented on src/Gateway.php
>  		// https://trello.com/c/i6GUZACP/83-reference-kentt%C3%A4%C3%A4n-woon-tilausnumero
This link should be removed

2024-04-17 13:09 UTC, loueranta-paytrail commented on src/Gateway.php
> +				'title' => __( 'Enable specific settlements', 'paytrail-for-woocommerce' ),
This should be renamed to "Enable individual settlements"

2024-04-18 05:56 UTC, loueranta-paytrail submitted a review, later dismissed

2024-04-18 07:28 UTC, chrisgan requested changes

2024-04-18 07:28 UTC, chrisgan commented on src/Gateway.php
> +			update_post_meta( $order_id, '_paytrail_ppa_transaction_settlement', true );
Any actions on the orders now need to be HPOS compliant. See https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book

For example this should be replaced with a $order->update_meta_data

You also need to ensure that $order->save() is called to make sure the data is updated. But this should be called as little as possible for performance reasons.

2024-04-18 07:28 UTC, chrisgan commented on src/Gateway.php
> +			update_post_meta( $order->get_id(), '_paytrail_ppa_transaction_settlement', true );
HPOS again

2024-04-18 11:55 UTC, loueranta-paytrail approved these changes

2024-04-18 11:57 UTC, merged